spring:
  application:
    name: skill-market
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/skill_market}
    username: ${DB_USERNAME:skill_market}
    password: ${DB_PASSWORD:skill_market}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    mapping-resources:
      - persistence/skill-market-orm.xml
